# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      snap install hugo --channel=extended
      echo install hugo complete
      snap install git-ubuntu
      git clone https://github.com/Vedabahu/bwebs ./bwebs
      cd bwebs
      hugo
      cd public

    displayName: "Install Hugo and do all the stuff"
