baseURL: 'https://vedabahu.github.io/bwebs/'
languageCode: en-us
title: Acme Corporation
theme: Electric
enableRobotsTXT: true
author: 
  facebook: "https://facebook.com"
  twitter: "https://twitter.com"
  github: "https://github.com/Vedabahu"
  name: "Acme Corporation"
  location: India
  phone: (91) 90000 90000

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 1
    - identifier: contact
      name: Contact
      url: /contact
      weight: 2

params:
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Acme Corporation.
    All Rights Reserved." 
  footer:
    - title: About
      content: >
        Acme Corporation is the world's leading
        manufacturer of digital shapes. From squares and
        circles to triangles and hexagons, we have it
        all. Browse through our collection of various
        forms with different thicknesses and line styles.
        We shape the world. You live in it.


    - title: Recent Blog Posts
      recents: blog
      recentCount: 7
    - title: Contact Us
      contact: true