baseURL = "http://example.com"
languageCode = "en-us"
title = "Acme Corporation"
theme = "Electric"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[author]
# facebook = "https://facebook.com"
twitter = "https://twitter.com"
github = "https://github.com/Vedabahu"
name = "Acme Corporation"
location = "India"
phone = "(91) 90000 90000"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 2

[params]
copyright = "Copyright &copy; 2022 Acme Corporation. All Rights Reserved."

[[params.footer]]
title = "About"
content = """
Acme Corporation is the world's leading manufacturer of digital shapes. From squares and circles to triangles and hexagons, we have it all. Browse through our collection of various forms with different thicknesses and line styles. We shape the world. You live in it.
"""

[[params.footer]]
title = "Recent Blog Posts"
recents = "blog"
recentCount = 7

[[params.footer]]
title = "Contact Us"
contact = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
lineNos = true
